Code Changes
avinashdckap/Palli-Application pull request #46
Opened 2023-12-04 07:12 UTC by Parasuramandckap

1. Code changes are done in the file I worked on.
2. Added a custom hook separately for the handle changes
3. Made a separate component for data limit and search
4. Added them by keeping the promise all method as you said to list the add task page students
5. Added a tooltip and handle cancel

Discussion:
I have written a functionality to display the deadline date in the response data and if the deadline is today in the antd tag, it will be shown as the deadline. But it's not working properly, tell me if you get an error in it

2023-12-07 06:32 UTC, avinashdckap requested changes

2023-12-07 06:32 UTC, avinashdckap commented on package-lock.json
Remove this changes !

2023-12-07 06:32 UTC, avinashdckap commented on src/components/BreadCrumbs.jsx
> +//external package
Just add a space between third party imports and custom imports and remove the //external package comments

2023-12-07 06:32 UTC, avinashdckap commented on src/components/CommonFilters.jsx
> +    </>
Include Total Records in this component

2023-12-07 06:32 UTC, avinashdckap commented on src/components/CommonFilters.jsx
> +const CommonFilter = ({ handleSearch, handleLimit, handleName ,handleChange}) => {
S missing in component name

2023-12-07 06:32 UTC, avinashdckap commented on src/components/CommonFilters.jsx
> +          style={{ width: 70, paddingLeft: 10, paddingRight: 5 }}
Inline styling remove it and add classnames

2023-12-07 06:32 UTC, avinashdckap commented on src/components/TableView.jsx
> +const TableComponent = ({ data, coulmnNameList, handleDelete, handleEdit }) => {
Change it as Table View name

2023-12-07 06:32 UTC, avinashdckap commented on src/hooks/useAPI.jsx
Change useAPI  implementation to normal axios request

2023-12-07 06:32 UTC, avinashdckap commented on src/hooks/useForm.jsx
Try react-hook-form for all the inputs in all pages

2023-12-07 14:11 UTC, ParasuramanA commented on src/components/CommonFilters.jsx
> +    </>
added

2023-12-07 14:11 UTC, Parasuramandckap commented on src/components/CommonFilters.jsx
> +const CommonFilter = ({ handleSearch, handleLimit, handleName ,handleChange}) => {
solved

2023-12-07 14:13 UTC, Parasuramandckap commented on src/components/TableView.jsx
> +const TableComponent = ({ data, coulmnNameList, handleDelete, handleEdit }) => {
This component is renamed

2023-12-09 06:31 UTC, avinashdckap approved these changes

2023-12-09 06:32 UTC, merged